// Generated by CoffeeScript 1.3.3
(function() {
  var codeHtml, codeJoin, codeSamples, codeSplit, j, preEscape;

  codeHtml = function(json) {
    return json["query"]["pages"]["1514"]["revisions"][0]["*"];
  };

  codeSamples = function(html) {
    var arr, codeReg, samples;
    codeReg = /<lang.*?>([.\s\S]*?)<\/lang>/g;
    samples = [];
    while ((arr = codeReg.exec(html))) {
      samples.push(arr[1]);
    }
    return samples;
  };

  j = function(s) {
    return JSON.stringify(s);
  };

  codeSplit = function(code) {
    var char, token, tokens, _i, _len;
    tokens = [];
    token = "";
    for (_i = 0, _len = code.length; _i < _len; _i++) {
      char = code[_i];
      if (char === " ") {
        if (token.length === 0 || token[token.length - 1] === " ") {
          token = token.concat(" ");
        } else {
          tokens.push(token);
          token = "";
        }
      } else if (char === "\n") {
        token = token.concat(char);
        tokens.push(token);
        token = "";
      } else {
        token = token.concat(char);
      }
    }
    tokens.push(token);
    return tokens;
  };

  codeJoin = function(splitCode) {
    var output, token, _i, _len;
    output = "";
    for (_i = 0, _len = splitCode.length; _i < _len; _i++) {
      token = splitCode[_i];
      console.log("Token:" + token);
      if (token[token.length - 1] !== "\n") {
        output += token + " ";
        console.log("outout:" + output);
      } else {
        output += token;
      }
    }
    return output;
  };

  preEscape = function(preCode) {
    var char, output, _i, _len;
    output = "";
    for (_i = 0, _len = preCode.length; _i < _len; _i++) {
      char = preCode[_i];
      if (char === "<") {
        output = output.concat("&lt;");
      } else if (char === ">") {
        output = output.concat("&gt;");
      } else if (char === "&") {
        output = output.concat("&amp;");
      } else {
        output = output.concat(char);
      }
    }
    return output;
  };

  jQuery(function() {
    var html, resp, sample, splitCode;
    resp = {
      "query": {
        "pages": {
          "1514": {
            "pageid": 1514,
            "ns": 0,
            "title": "Hello world\/Text",
            "revisions": [
              {
                "*": "=={{header|C}}==\n{{works with|gcc|4.0.1}}\n<lang c>#include <stdlib.h>\n#include <stdio.h>\n\nint main(void)\n{\n  printf(\"Goodbye, World!\\n\");\n  return EXIT_SUCCESS;\n}<\/lang>\nOr:\n<lang c>#include <stdlib.h>\n#include <stdio.h>\n\nint main(void)\n{\n  puts(\"Goodbye, World!\");\n  return EXIT_SUCCESS;\n}<\/lang>"
              }
            ]
          }
        }
      },
      "query-continue": {
        "revisions": {
          "rvstartid": 137809
        }
      }
    };
    html = codeHtml(resp);
    $("body").append("<pre>" + html + "</pre>");
    sample = codeSamples(html)[0];
    console.log(sample);
    splitCode = codeSplit(sample);
    console.log(splitCode);
    $("body").append("=====<br /><pre>" + escape(codeJoin(splitCode)) + "</pre>");
    return $("body").append("=====<br /><pre>" + preEscape(codeJoin(splitCode)) + "</pre>");
  });

}).call(this);
